spring.application.name=medical-management
spring.datasource.url=jdbc:mysql://localhost:3306/medical_db
spring.datasource.username=root
spring.datasource.password=harshad200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
